### ISSUE TITLE
tsidFactory.Generate not thread-safe.

### ISSUE THREAD

**Issue by Rosario9527** [vishal-bihani/go-tsid#3]
Hi, There,

1. tsidFactory.Generate not thread safe, cause factory.counter++ and  factory.counter = value
2. tsidFactory and tsid not public, i can't declare it..  var factory *tsid.tsidFactory, var id *tsid.tsid, i need few factories, so i need to declare it

**Comment by vishal-bihani** [comment]
Thanks for raising this. #1 is fixed.  #2 should be taken separately.
